name: Daily Scan
on:
  schedule:
    - cron: '24 06 * * *'
  workflow_dispatch:
jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run
        env:
          DAILY_EMAIL_PASS: ${{ secrets.DAILY_EMAIL_PASS }}
        run: python automation_script.py
